build:
  nodes:
    analysis:
      project_setup:
        override: ['true']
      tests:
        override: ['php-scrutinizer-run']
  environment:
    timezone: UTC
    php:
      version: 7.1
      ini:
        date.timezone: 'US/Pacific'
        memory_limit: '-1'

